# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: sandor
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: berlin
    ports:
      - '5432:5432'
  adminer:
    image: adminer
    restart: always
    ports:
      - 8083:8080