name: Build and push backend to DigitalOcean Container Registry

env:
  IMAGE_TAG: '0.1'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22.9.0'

    - name: Log in to DigitalOcean Container Registry
      run: echo "${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}" | docker login registry.digitalocean.com -u "${{ secrets.DIGITALOCEAN_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: |
        docker build -t registry.digitalocean.com/artifact-store/berlin:berlin-api-${{env.IMAGE_TAG}} .

    - name: Push to DigitalOcean Container Registry
      run: |
        docker push registry.digitalocean.com/artifact-store/berlin:berlin-api-${{env.IMAGE_TAG}}